### ISSUE TITLE
Package doesn't sucessfully build when installing on Windows 11

### ISSUE THREAD

**Issue by the-nth-ace** [expedock/strawberry-sqlalchemy-mapper#8]
Below is the error stack

```console 
Collecting strawberry-sqlalchemy-mapper
  Downloading strawberry-sqlalchemy-mapper-0.1.0.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-nlvmub9p\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-nlvmub9p\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-nlvmub9p\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 14, in <module>
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1135, in read_text
          return f.read()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode     
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 3209: character maps to <undefined>      
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

It installs successfully on WSL2 running Ubuntu 22.04.1

**Comment by raguiar2** [comment]
We unfortunately haven't built this library to run outside of WSL on a windows machine. If you want to submit a pull request to fix the error, feel free to do so!

**Comment by HealYouDown** [comment]
Hey @raguiar2 , I created a pull request to fix this issue.

Could you merge the pull request and update the package on PyPi? Would help me out a lot!

Thanks! :)

**Comment by TimDumol** [comment]
> Hey @raguiar2 , I created a pull request to fix this issue.
> 
> Could you merge the pull request and update the package on PyPi? Would help me out a lot!
> 
> Thanks! :)

Done!
